### ISSUE TITLE
improve stability, better error-handling

### ISSUE THREAD

**Issue by Steve2955** [Steve2955/md2anki#14]
Es gibt einige Punkte, an denen wir vielleicht sinnvolle Fehlermeldungen ausgeben sollten oder noch ein paar Fehler auffangen könnten:

- [ ] I/O-Fehler mit files
  - [ ] Output wird standardmäßig überschrieben (`-f` wäre wahrscheinlich eine gute Idee)
- [ ] Bilder existieren nicht (als file)
- [ ] Fehler beim Markdown-Parsen/Rendern
- [ ] keine Karten gefunden bzw. alle ignoriert

Soweit nur das, was mir spontan eingefallen ist. Da gibt's vielleicht noch ein paar Sachen mehr.

**Comment by RvNovae** [comment]
>  Output wird standardmäßig überschrieben (-f wäre wahrscheinlich eine gute Idee)

Meinst du damit, dass man einen `-f` Parameter hinzufügen soll, der die `apkg` überschreibt und ansonsten wirft man einen Fehler, wenn die Datei schon existiert?

**Comment by Steve2955** [comment]
> >  Output wird standardmäßig überschrieben (-f wäre wahrscheinlich eine gute Idee)
> 
> Meinst du damit, dass man einen `-f` Parameter hinzufügen soll, der die `apkg` überschreibt und ansonsten wirft man einen Fehler, wenn die Datei schon existiert?

Ja, hätte ich mir so vorgestellt oder meinst du das ist weniger sinnvoll?

**Comment by RvNovae** [comment]
Hmhm bin mir nicht sicher. 
Ist wahrscheinlich relativ egal, weils ja dann sowieso hauptsächlich als Action ausgeführt wird, oder?

**Comment by Steve2955** [comment]
Hast schon recht, letztlich wird's Niemanden interessieren 😅
