### ISSUE TITLE
npm release

### ISSUE THREAD

**Issue by Steve2955** [Steve2955/md2anki#15]
Wenn das Teil hier halbwegs funktionstüchtig ist, würde ich es auch in die Package-Registries packen. Leider ist [`md2anki`](https://www.npmjs.com/package/md2anki) und [`mdanki`](https://www.npmjs.com/package/mdanki) schon vergeben. Hat jemand zufällig ne ultra kreative Idee oder läuft es auf sowas wie `@Steve2955/md2anki` hinaus? Den Befehl sollte man dann bei einer globalen Installation *(vermutlich)* trotzdem als `md2anki` verwenden können. Aber das muss ich mir nochmal anschauen.

**Comment by RvNovae** [comment]
- m2anki
- md2a
- md2apkg

würden mir spontan einfallen

**Comment by Steve2955** [comment]
`md2apkg` ist gut, das muss ich mir glaube reservieren 😄

**Comment by Steve2955** [comment]
[Version 1.0.0 is released to npm 🎉](https://www.npmjs.com/package/md2apkg)

**Comment by RvNovae** [comment]
> [Version 1.0.0 is released to npm 🎉](https://www.npmjs.com/package/md2apkg)

Awesome! We should probably create an entry under https://github.com/Steve2955/md2apkg/releases/new
