### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by tricktux** [Steve2955/md2anki#25]
I would like to start by expressing how excited I am about `md2anki`. I've followed [mdanki][0] for a long time. However, the issue with exports overriding cards, it's truly a deal breaker. Cards, get added and modified all the time. It's truly exciting that you guys were able to fix this issue!

Couple of useful features I would like to request from [mdanki][0] are:

1. Ability to extend card front with `%`.
2. Code highlighting

BTW: The latex handling it's pretty awesome.
I've also been following, issue #15 

Thanks again for the great work!

[0]: https://github.com/ashlinchak/mdanki

**Comment by Steve2955** [comment]
Thank you very much for those kind words. The ability to extend card fronts is on the top of my list as well. However, I intend to use an html-comment syntax for splitting card back and front by default (something like `<!-- md2anki split -->`). Considering your use case I will add optional compatibility with the mdanki-%-syntax.

I will be working on this as well as #15 on the weekend. I thought about syntax-highlighting for code blocks as well, but that might take some more time.

**Comment by RvNovae** [comment]
Perhaps we could use something like https://highlightjs.org/ for syntax highlighting?

1. Search for code tags in HTML
2. run that through highlightJS
3. profit?

**Comment by Steve2955** [comment]
`highlightjs` is what I had in my mind as well. It's also the [recommended way by](https://github.com/markdown-it/markdown-it#syntax-highlighting) `markdown-it`.

@RvNovae Do you might want to implement syntax highlighting? I already did some work on the "extending card fronts"-feature. A PR should be ready for review this evening.

**Comment by RvNovae** [comment]
> `highlightjs` is what I had in my mind as well. It's also the [recommended way by](https://github.com/markdown-it/markdown-it#syntax-highlighting) `markdown-it`.
> 
> @RvNovae Do you might want to implement syntax highlighting? I already did some work on the "extending card fronts"-feature. A PR should be ready for review this evening.

Yeah sounds good, I can take a look at it over the weekend.

**Comment by tricktux** [comment]
@Steve2955 Thank you much for considering the requests! Really looking forward to that code highlight!
