### ISSUE TITLE
Title falsch formatiert

### ISSUE THREAD

**Issue by jsuesse** [Steve2955/md2anki#32]
![image](https://user-images.githubusercontent.com/26322754/139525598-22f77a04-df24-43bf-9e54-18f7cabbf3e1.png)
![image](https://user-images.githubusercontent.com/26322754/139525605-a8407ab0-6ea8-4e97-959f-0accb2c43f93.png)
![image](https://user-images.githubusercontent.com/26322754/139525613-fe5d1402-aa7f-469f-8a23-93539543a1ed.png)

**Comment by RvNovae** [comment]
Kann ich nachstellen. Vielleicht sollte man mal einen Sonderfall dafür einbauen, wenn der Titel so speziell definiert ist, wie bei uns. Wundert mich aber ehrlich gesagt, wie das Ding überhaupt erkannt wird.
