### ISSUE TITLE
Bug: Use package locally

### ISSUE THREAD

**Issue by daniel-vera-g** [Steve2955/md2anki#34]
Hey :wave: , I was searching for a package to replace md2anki as it overrides cards when updating the deck. Your package seems to be a good replacement., thanks for that.

Nevertheless, it seems that using the Package by installing it locally does not work. You can see my example attached. If I install the package(`npm i md2apkg`) and then run it by doing `npx md2apkg capitals.md`(Or use it with `npm run ...`)  it seems to stop somewhere in this function: https://github.com/Steve2955/md2apkg/blob/main/src/index.js#L131

```
➜ npx md2apkg capitals.md
found 50 cards!
```

It would be helpful, if it could be avoided to having to install it globally.

[anki-test.zip](https://github.com/Steve2955/md2apkg/files/7456341/anki-test.zip)

**Comment by Steve2955** [comment]
Hey, 
thank you very much for including a lot of details in your issue and even providing the sample. 
I think this should be fixed easily :D

Greeting to Karlsruhe 👋

**Comment by Steve2955** [comment]
Resolved by #36
