### ISSUE TITLE
Exceed Max Memory with too much cards

### ISSUE THREAD

**Issue by daniel-vera-g** [Steve2955/md2anki#39]
I was using a Deck with a little bit more of content and a higher number of cards.  
By trying to compile, I would get a Memory issue:

```shell
➜ md2apkg -i test.md
found 71 cards!
writeStringToMemory is deprecated and should not be called! Use stringToUTF8() instead!
deck initialized!
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile w
ith  -s ABORTING_MALLOC=0
```

### Test

To test, use my attached file and use the `md2apkg` package: `npm init -y && npm i md2apkg && npx md2apkg -i test.md`

[test.md](https://github.com/Steve2955/md2apkg/files/7721094/test.md)

### Workaround/Fix

The issue comes from the [anki-pkg-export](https://github.com/repeat-space/anki-apkg-export/issues?q=memory) package.

I saw, that there was a comment with a way to probably fix this: https://github.com/repeat-space/anki-apkg-export/issues/25#issuecomment-317842407  and that you're currently also maintaining the `anki-apkg-export` fork for this package. Would it be possible to implement the proposed change in `md2apkg` ?

Currently I'm using [this](https://github.com/repeat-space/anki-apkg-export/issues/32#issuecomment-471487976) as a workaround. Nevertheless, that's clearly not the solution as people using this package don't know about this upstream Issue 😅

**Comment by Steve2955** [comment]
@daniel-vera-g Thank you very much for pointing out this issue. Your provided example file didn't cause any issues for me at first, but after appending the file a few times to itself the error showed up. I pushed a fix to my fork of [anki-apkg-export](https://github.com/Steve2955/anki-apkg-export/commit/711816676b3f564c05d16d17f17df78228895538). No changes to md2apkg were required.

Sorry for taking a few weeks to do this, I've been a bit busy lately. Let me know if this fixed your issue. :)

**Comment by daniel-vera-g** [comment]
Fixed it, thanks.
Closing it 👍
