### ISSUE TITLE
implement support for latex

### ISSUE THREAD

**Issue by Steve2955** [Steve2955/md2anki#4]
I already tried adding support for LaTeX using `markdown-it-texmath` and `katex`. However, that didn't work out first try. Also it would bloat our decks quite a bit when including alot of custom css and custom fonts.

So for implementing this, we should probably stick to the [official way](https://docs.ankiweb.net/math.html). But I will have to look into this again.

**Comment by RvNovae** [comment]
Wenn ich das richtig sehe, müssen wir ja zunächst erstmal nur `$...$` mit `[$]...[/$}` austauschen, oder? 🤔

**Comment by Steve2955** [comment]
Nicht ganz, aus `$...$` wird `\(...\)` und aus  `$$...$$` wird `\[...\]`.

[Hab damit auch gerade rumgespielt](https://github.com/Steve2955/md2anki/tree/latex-test) 😅

**Comment by Steve2955** [comment]
Ich dachte auch erst, es muss `[$]...[/$}` werden, aber Anki hat das iwie nicht gefallen, weil der da noch die extra Tags drumbastelt: `\begin{math}...\end{math}`

**Comment by RvNovae** [comment]
Hmhm okay, aber wenn ich in Anki `[$]\rightarrow[/$]` eingebe, bekomme ich folgendes:
![image](https://user-images.githubusercontent.com/11728465/125135747-d0dc8400-e109-11eb-97c7-9b3e7fd22ac9.png)

**Comment by RvNovae** [comment]
> Ich dachte auch erst, es muss `[$]...[/$}` werden, aber Anki hat das iwie nicht gefallen, weil der da noch die extra Tags drumbastelt: `\begin{math}...\end{math}`

hmm okay, interesting

**Comment by Steve2955** [comment]
Ich fand die Idee eigentlich ganz schon, das direkt im Parsing/Render-Schritt von `markdown-it` zu machen. Hab damit einiges rumgespielt, bin aber kläglich gescheitert. Deshalb steht in der Branch jetzt erstmal ne modifizierte Kopie von [`texmath`](https://github.com/goessner/markdown-it-texmath/blob/master/texmath.js).

**Comment by Steve2955** [comment]
Oder meinst du es reicht, wenn wir im fertigen HTML etwas rumpfuschen? 😂

**Comment by RvNovae** [comment]
> Oder meinst du es reicht, wenn wir im fertigen HTML etwas rumpfuschen? 😂

Haha, in der Not bin ich für jede Pfuscherei zu haben 😁

> Ich fand die Idee eigentlich ganz schon, das direkt im Parsing/Render-Schritt von `markdown-it` zu machen. Hab damit einiges rumgespielt, bin aber kläglich damit gescheitert. Deshalb steht in der Branch jetzt erstmal ne modifizierte Kopie von [`texmath`](https://github.com/goessner/markdown-it-texmath/blob/master/texmath.js).

Ah jo. Ich hab eben nur mal einen kurzen Blick drauf geworfen, vielleicht schau es mir auch später selbst nochmal an.

**Comment by Steve2955** [comment]
> Haha, in der Not bin ich für jede Pfuscherei zu haben 😁

Also da sich das Ganze somit auf [drei Zeilen](https://github.com/Steve2955/md2anki/compare/latex-test) reduziert, bin ich auch für das Pfuschen 😅
