### ISSUE TITLE
front of card with text out header broken in latest version of anki

### ISSUE THREAD

**Issue by tricktux** [Steve2955/md2anki#42]
Let me start by saying that I love this plugin

Been using it for years!

But in the more recent versions of Anki:
![image](https://github.com/Steve2955/md2apkg/assets/5428479/e36d05ad-7813-46ce-bd1a-ce8df1759884)

This type of card is broken:
```md
## What's the difference between `read` and `recv`?

Enter any text here

<!-- meta pkg split -->

- The argument `flags`
- `recv` with `flags = 0` is basically a `read`

![1](attachements/2024-05-24-16-31-03.png)
```

Without the non header text the front and back of the anki card  good. With it the front and back get mixed, and the back is kind of broken.

Software version:
![image](https://github.com/Steve2955/md2apkg/assets/5428479/4b48a25a-a15d-46d5-9ab4-04842495ca29)

**Comment by Steve2955** [comment]
Thanks for the appreciation of my work. To be honest I haven't used it much myself lately, but I still gave it a quick look:

I installed the latest version of Anki (`Version ⁨24.04.1 (ccd9ca1a)⁩ Python 3.9.18 Qt 6.6.2 PyQt 6.6.1`) and converted a slightly adjusted version of your example to an Anki deck which I imported right after:


```md
## What's the difference between `read` and `recv`?

Enter any text here

<!-- meta pkg split -->

- The argument `flags` xxxx
- `recv` with `flags = 0` is basically a `read`
```

```bash
md2apkg -i TEST.md -n GH-TEST
```

After importing, the card looks like this:

![image](https://github.com/Steve2955/md2apkg/assets/21085384/d4d31888-4aa1-4c65-89f2-3be2ac91ec61)

This is excatly how I would expect it to look like. The html comment (`<!-- meta pkg split -->`) is ignored as it is not the expected format of `<!-- md2apkg split -->`. ([see README](https://github.com/Steve2955/md2apkg?tab=readme-ov-file#custom-markdown-extensions))

If you use this syntax:

```md
## What's the difference between `read` and `recv`?

Enter any text here

<!-- md2apkg split -->

- The argument `flags` xxxx
- `recv` with `flags = 0` is basically a `read`
```

The card get's also split into front and back as expected:

![image](https://github.com/Steve2955/md2apkg/assets/21085384/e7d3b0a9-27fd-4cb6-82da-1073ec933527)

Is it possible, that you just switched up the html comment? If not, could you please provide a further example that helps me to reproduce the issue?

**Comment by tricktux** [comment]
Ohhhh waoooo 

Where did I get that split tag? That's really crazy. I guess I messed up a while back and it was just working, until  more recently that I tried more text in the front.

Nothing to see here :)

Thank you much for the quick response!!

**Comment by Steve2955** [comment]
Alright, that was an easy fix 😄 

No worries and thank you very much again for the appreciation!
